#!/usr/bin/env bash
# Transfers a file from a client to a server:
# Accepts 4 parameters:
## 1:Path to the file to transfer
## 2:IP of the server where to transfer the file to
## 3:Username scp connects with in the server
## 4:Path to the SSH private key that scp uses

if [ $# -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
