#!/usr/bin/env bash
# Install nginx and configure it.

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
}
EOL

nginx -s stop
nginx
