#!/usr/bin/env bash
# Install and configure nginx to redirect incomming redirect_me/ request.

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

nginx -s stop
nginx
