#!/usr/bin/env bash                                                                                                                    
# find out what’s keeping your Ubuntu container’s Nginx installation
# from listening on port 80

if ! command -v nginx &> /dev/null; then
	sudo apt update && sudo apt upgrade -y
	sudo apt install nginx -y
fi

cd /etc/nginx/sites-enabled/ || exit
rm default

ln -s /etc/nginx/sites-available/default default

sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

service nginx restart
